version: '3.8'
services:
  mysql_server:
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=blackjack
      - MYSQL_USER=app
      - MYSQL_PASSWORD=toor
      - MYSQL_ROOT_HOST=%
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password


